site_name: Resumos para prova
site_author: Gustavo Fellipe
site_url: https://gustavoifrn.github.io/portif-web/

# Repositório
repo_url: https://github.com/Gustavoifrn/portif-web

# Para publicação no servidor web local
#site_dir: /var/www/html

theme:
  name: material
  language: pt
  features:
    - content.action.edit

# Ativa extensões do Markdown (Ex.: Emojis)
markdown_extensions:
  - pymdownx.emoji

# Habilita diagramas com a linguagem Mermaid JS
plugins:
    - mermaid2